import { BASE_STAGE_WAVE_PROFILES } from "../../wave-engine/constants/stageWaveProfiles";

export const STAGE_PULSE_PROFILES = {
  awake: {
    brightnessBias: 1.02,
    clustering: 0.18,
    intentionality: 0.86,
    pulseRateMultiplier: 1.25,
    pulseTypeWeights: BASE_STAGE_WAVE_PROFILES.awake.values,
    randomness: 0.72,
    regionWeights: {
      central: 0.2,
      frontal: 0.17,
      occipital: 0.23,
      parietal: 0.23,
      temporal: 0.17,
    },
    sizeBias: 0.92,
    synchronization: 0.24,
  },
  deep: {
    brightnessBias: 0.92,
    clustering: 0.72,
    intentionality: 0.88,
    pulseRateMultiplier: 0.62,
    pulseTypeWeights: BASE_STAGE_WAVE_PROFILES.deep.values,
    randomness: 0.22,
    regionWeights: {
      central: 0.23,
      frontal: 0.34,
      occipital: 0.13,
      parietal: 0.17,
      temporal: 0.13,
    },
    sizeBias: 0.98,
    synchronization: 0.84,
  },
  light: {
    brightnessBias: 0.98,
    clustering: 0.34,
    intentionality: 0.52,
    pulseRateMultiplier: 0.92,
    pulseTypeWeights: BASE_STAGE_WAVE_PROFILES.light.values,
    randomness: 0.48,
    regionWeights: {
      central: 0.26,
      frontal: 0.24,
      occipital: 0.15,
      parietal: 0.16,
      temporal: 0.19,
    },
    sizeBias: 0.96,
    synchronization: 0.46,
  },
  rem: {
    brightnessBias: 1.04,
    clustering: 0.46,
    intentionality: 0.58,
    pulseRateMultiplier: 1.08,
    pulseTypeWeights: BASE_STAGE_WAVE_PROFILES.rem.values,
    randomness: 0.7,
    regionWeights: {
      central: 0.18,
      frontal: 0.12,
      occipital: 0.2,
      parietal: 0.22,
      temporal: 0.28,
    },
    sizeBias: 0.94,
    synchronization: 0.4,
  },
};
